name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: alway

jobs:
  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: minecraft-regions-tool
        path: target/release/minecraft-regions-tool
      
  build_windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: minecraft-regions-tool.exe
        path: target/release/minecraft-regions-tool.exe
